version: '3.9'

services:

  skywars:
    build: ../..
    command: gunicorn --bind 0.0.0.0:80 run:app
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - 25000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.confvolumes
    restart: always

    healthcheck:
       test: ["CMD-SHELL"]
       interval: 5s
       timeout: 5s
       retries: 5